FROM registry.cn-shanghai.aliyuncs.com/c7n/javabase:0.10.1
WORKDIR /choerodon
COPY app.jar prod-repo-service.jar
COPY dist dist
RUN chmod +x /choerodon/dist/env.sh \
    && chown -R www-data:www-data /choerodon
USER 33
CMD /choerodon/dist/env.sh java $JAVA_OPTS $SKYWALKING_OPTS -jar /choerodon/prod-repo-service.jar